#================================================== -*- makefile -*- vim:ft=make
# Copyright 2014-2017 Intel Corporation
# All Rights Reserved.
#
# If this  software was obtained  under the  Intel Simplified  Software License,
# the following terms apply:
#
# The source code,  information  and material  ("Material") contained  herein is
# owned by Intel Corporation or its  suppliers or licensors,  and  title to such
# Material remains with Intel  Corporation or its  suppliers or  licensors.  The
# Material  contains  proprietary  information  of  Intel or  its suppliers  and
# licensors.  The Material is protected by  worldwide copyright  laws and treaty
# provisions.  No part  of  the  Material   may  be  used,  copied,  reproduced,
# modified, published,  uploaded, posted, transmitted,  distributed or disclosed
# in any way without Intel's prior express written permission.  No license under
# any patent,  copyright or other  intellectual property rights  in the Material
# is granted to  or  conferred  upon  you,  either   expressly,  by implication,
# inducement,  estoppel  or  otherwise.  Any  license   under such  intellectual
# property rights must be express and approved by Intel in writing.
#
# Unless otherwise agreed by Intel in writing,  you may not remove or alter this
# notice or  any  other  notice   embedded  in  Materials  by  Intel  or Intel's
# suppliers or licensors in any way.
#
#
# If this  software  was obtained  under the  Apache License,  Version  2.0 (the
# "License"), the following terms apply:
#
# You may  not use this  file except  in compliance  with  the License.  You may
# obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#
#
# Unless  required  by   applicable  law  or  agreed  to  in  writing,  software
# distributed under the License  is distributed  on an  "AS IS"  BASIS,  WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# See the   License  for the   specific  language   governing   permissions  and
# limitations under the License.
#===============================================================================

##  Content:
##     Intel(R) Data Analytics Acceleration Library algorithms list
##******************************************************************************

naivebayes += classifier
svm += classifier kernel_function
em += covariance
adaboost += boosting weak_learner
weak_learner += stump
neural_networks/initializers += engines engines/mt19937
neural_networks/layers += neural_networks/initializers/uniform
neural_networks/layers/fullyconnected_layer += neural_networks/layers/fullyconnected_layer/backward \
                                               neural_networks/layers/fullyconnected_layer/forward  \
                                               neural_networks/layers/loss_layer                    \
                                               neural_networks/layers
neural_networks/layers/loss_layer/softmax_cross_layer += neural_networks/layers/loss_layer/softmax_cross_layer/backward \
                                                         neural_networks/layers/loss_layer/softmax_cross_layer/forward  \
                                                         neural_networks/layers/loss_layer                              \
                                                         neural_networks/layers                                         \
                                                         neural_networks/layers/softmax_layer/forward                   \
                                                         neural_networks/layers/softmax_layer/backward                  \
                                                         neural_networks/layers/softmax_layer
neural_networks += neural_networks/layers objective_function optimization_solver optimization_solver/sgd neural_networks/layers/loss_layer
k_nearest_neighbors += classifier
decision_tree += classifier regression
linear_model += regression
linear_regression += linear_model
ridge_regression += linear_model

CORE.ALGORITHMS.FULL :=                                                       \
    implicit_als                                                              \
    classifier                                                                \
    kernel_function                                                           \
    distributions                                                             \
    distributions/bernoulli                                                   \
    distributions/normal                                                      \
    distributions/uniform                                                     \
    engines                                                                   \
    engines/mt19937                                                           \
    svm                                                                       \
	mf_sgd

CORE.ALGORITHMS := $(if $(CORE.ALGORITHMS.CUSTOM), $(CORE.ALGORITHMS.CUSTOM), $(CORE.ALGORITHMS.FULL))
CORE.ALGORITHMS := $(sort $(foreach alg,$(CORE.ALGORITHMS),$(foreach alg1,$($(alg)),$($(alg1)) $(alg1)) $(alg)))

CORE.ALGORITHMS.INC :=                                                        \
    implicit_als                                                              \
    classifier                                                                \
    kernel_function                                                           \
    distributions                                                             \
    engines                                                                   \
    svm                                                   					  \
	mf_sgd

CORE.SERVICES       := compression            \
                       data_management

JJ.ALGORITHMS       := 															 \
                       implicit_als                                              \
                       implicit_als/prediction                                   \
                       implicit_als/prediction/ratings                           \
                       implicit_als/training                                     \
                       implicit_als/training/init                                \
					   classifier                                                \
                       classifier/prediction                                     \
                       classifier/quality_metric                                 \
                       classifier/quality_metric/binary_confusion_matrix         \
                       classifier/quality_metric/multi_class_confusion_matrix    \
                       classifier/training                                       \
					   kernel_function                                           \
                       kernel_function/linear                                    \
                       kernel_function/rbf                                       \
					   distributions                                             \
                       distributions/bernoulli                                   \
                       distributions/normal                                      \
                       distributions/uniform                                     \
                       quality_metric                                            \
                       quality_metric_set                                        \
					   engines                                                   \
                       engines/mt19937                                           \
                       svm                                                       \
                       svm/prediction                                            \
                       svm/quality_metric_set                                    \
                       svm/training                                        		 \
					   mf_sgd

JJ.DATA_MANAGEMENT  := data                                                      \
                       data_source                                               \
                       compression                                               \
                       compression/bzip2                                         \
                       compression/lzo                                           \
                       compression/rle                                           \
                       compression/zlib

JJ.SERVICES         := libraryversioninfo
