#===============================================================================
# Copyright 2014-2016 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#===============================================================================

##  Content:
##     Intel(R) Data Analytics Acceleration Library algorithms list
##******************************************************************************

CORE.ALGORITHMS     := kmeans                                                    \
                       implicit_als                                              \
                       mf_sgd														  

CORE.ALGORITHMS.INC := kmeans                                                    \
                       implicit_als                                              \
					   mf_sgd													 

CORE.SERVICES       := compression

JJ.ALGORITHMS       := kmeans                                                    \
                       kmeans/init                                               \
                       implicit_als                                              \
                       implicit_als/prediction                                   \
                       implicit_als/prediction/ratings                           \
                       implicit_als/training                                     \
                       implicit_als/training/init                                \
                       mf_sgd                                                    

JJ.DATA_MANAGEMENT  := data                                                      \
                       data_source                                               \
                       compression                                               \
                       compression/bzip2                                         \
                       compression/lzo                                           \
                       compression/rle                                           \
                       compression/zlib

JJ.SERVICES         := libraryversioninfo
