cc_library(
    name = "harp-examples-data-generators",
    srcs = [
        "DataGenerator.cpp",
    ],
    hdrs = [
        "DataGenerator.h",
    ],
    visibility = ["//examples/kmeans:__pkg__"],
)
